[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dictionary_learning"
version = "0.1.0"
description = "A package for dictionary learning algorithms"

license = { text = "MIT" }